#!/usr/bin/env python3
"""COREDEV-2780 M2 — the trunk-check workflow against §1's contract.

Owns cells 4, 9, 14 and 15, cell 10's STATIC half, and cell 11's mutant generation.

WHY THE ORACLE IS FROZEN HERE AND NOT READ FROM THE TREE. The hazard this ticket exists to close is a
gate that reports green having checked nothing, and its most seductive form is an assertion that reads
its expectation out of the artifact under test: a silently reduced configuration then becomes
AUTHORITATIVE OVER THE ASSERTION MEANT TO DETECT IT. So the nineteen linter names, the runner, the
timeout, the action SHA and the argument literal are literals here.

WHAT CELL 11 DOES. It does not carry a hand-written mutant list — every earlier revision of this plan
had one and every round found a different member missing. Mutants are GENERATED by iterating the
mutation CASES in docs/planning/COREDEV-2780-contract.yaml, so under-coverage is impossible by
construction rather than by assertion. Each generated mutant must be CONSTRUCTIBLE, must change the
intended property, and must fail with ITS OWN diagnostic — a mutant killed through a sibling clause's
message proves reachability, not discrimination.
"""

from __future__ import annotations

import copy
import hashlib
import json
import re
import subprocess
import unittest
from pathlib import Path

import yaml

REPO = Path(__file__).resolve().parents[2]
WORKFLOW_PATH = REPO / ".github/workflows/trunk-check.yml"
RESOLVER_PATH = REPO / "scripts/ci/resolve-trunk-range.sh"
REGISTRY_PATH = REPO / "docs/planning/COREDEV-2780-contract.yaml"
SURVIVORS_PATH = REPO / "docs/planning/COREDEV-2780-survivors.yaml"
TRUNK_CONFIG = REPO / ".trunk/trunk.yaml"

# ---- frozen literals: the oracle, never derived from the artifact under test --------------------
ACTION_PIN = "trunk-io/trunk-action@e1234e67a86010d61ddac8d8ebf4b783e2ffd2fa"
ARGUMENTS_LITERAL = "--filter=-markdown-link-check"   # §6.4, stated once THERE and matched whole
EXPECTED_RUNNER = "ubuntu-latest"
EXPECTED_TIMEOUT_MINUTES = 15        # a CONCRETE ceiling; "a timeout exists" is satisfied by 360
EXPECTED_CONTEXT = "trunk-check"
EXPECTED_STEPS = ["checkout", "guard-resolver-digest", "guard-empty-diff", "guard-launcher-path", "trunk"]
C6_GUARDED_PATHS = (
    ".trunk/bin/trunk", "tools/trunk", "./trunk",
    ".trunk/setup-ci", ".trunk/user.yaml", ".trunk/env.yaml",
)
# 20 enabled minus §6.4's declared exclusion. Held as literals: a membership oracle regenerated from
# the config under test cannot detect that config being reduced.
EXPECTED_LINTERS = frozenset({
    "zizmor", "gitleaks", "trufflehog", "bandit", "checkov", "mypy", "ruff", "shellcheck",
    "actionlint", "pinact", "git-diff-check", "markdownlint", "codespell", "black", "isort",
    "prettier", "shfmt", "taplo", "yamllint",
})
EXCLUDED_LINTER = "markdown-link-check"

# M2 ships job-scoped `continue-on-error: true` and C3 forbids it. The exemption is JOB SCOPE ONLY and
# ends at M3, where cell 11's C3 cases are enabled. Asserting C3 at M2 would make the suite
# intentionally red; leaving the exemption unqualified would let step scope through, which would make
# cell 2's M2 half unobservable.
M2_ADVISORY_EXEMPTION = {"continue-on-error"}


def _load_workflow() -> dict:
    return yaml.safe_load(WORKFLOW_PATH.read_text(encoding="utf-8"))


def _on(workflow: dict):
    """YAML 1.1 parses a bare `on:` key as the boolean True."""
    return workflow.get("on", workflow.get(True))


def _root_keys(workflow: dict) -> set[str]:
    return {("on" if key is True else key) for key in workflow}


def _job(workflow: dict) -> dict:
    return workflow["jobs"][EXPECTED_CONTEXT]


def _steps(workflow: dict) -> list[dict]:
    return _job(workflow)["steps"]


def _step(workflow: dict, name: str) -> dict:
    return next(step for step in _steps(workflow) if step.get("name") == name)


def _sha256_file(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def _resolve_target_set() -> set[str]:
    """resolve(ref_name, default_branch) — ENTRY-AGNOSTIC, and the only implementation.

    include MINUS exclude; `~DEFAULT_BRANCH` expands to the repository's current default branch;
    `refs/heads/` is stripped; `~ALL` and any fnmatch metacharacter FAIL CLOSED, because a pattern
    denotes a set this contract cannot enumerate and treating it as a literal is how an over-broad
    target passes a set comparison.

    It takes no entry id and no entry-derived argument, so there is nothing to dispatch on and a
    per-entry private resolver cannot be written behind it. Callers resolve ONCE and pass the result
    into each entry's comparison.
    """
    ruleset = json.loads(subprocess.run(
        ["gh", "api", "repos/UnleashedServices/unleashed-mail-plugin/rulesets/16082567"],
        capture_output=True, text=True, check=True).stdout)
    default_branch = json.loads(subprocess.run(
        ["gh", "api", "repos/UnleashedServices/unleashed-mail-plugin"],
        capture_output=True, text=True, check=True).stdout)["default_branch"]
    return _resolve_ref_name(ruleset["conditions"]["ref_name"], default_branch)


def _resolve_ref_name(ref_name: dict, default_branch: str) -> set[str]:
    def expand(entry: str) -> str:
        if entry == "~ALL" or any(ch in entry for ch in "*?["):
            raise ValueError(f"target set unresolvable: refusing to enumerate {entry!r}")
        if entry == "~DEFAULT_BRANCH":
            return default_branch
        return entry[len("refs/heads/"):] if entry.startswith("refs/heads/") else entry

    include = {expand(entry) for entry in ref_name.get("include", [])}
    exclude = {expand(entry) for entry in ref_name.get("exclude", [])}
    return include - exclude


def _normalised_lint_block(config_text: str) -> str:
    """The `lint:` block with VERSION SPECIFIERS normalised out, then hashed.

    A whole-block byte digest and the version-bump carve-out cannot both hold: `.trunk/trunk.yaml`
    carries versions inline (`zizmor@1.29.0`), so a routine `trunk upgrade` would red the cell with no
    plan change — and the obvious repair, regenerating the expectation from the config under test, is
    exactly the coupling the freeze exists to remove. Normalising versions before hashing still catches
    a changed `commands[].run`, a widened `success_codes`, an added `ignore` or a dropped linter, and
    ignores the one edit that is routine.
    """
    block = yaml.safe_load(config_text)["lint"]
    return re.sub(r"@\d+[\w.\-+]*", "@<version>", yaml.safe_dump(block, sort_keys=True))


def contract_problems(workflow: dict, *, milestone: str = "M2") -> list[str]:
    """§1's contract, clause by clause, as diagnostics. Cell 11 mutates against THIS."""
    problems: list[str] = []
    on = _on(workflow)
    job = _job(workflow)
    steps = _steps(workflow)
    names = [step.get("name") for step in steps]

    # C0 — the workflow ROOT mapping is an allowlist, and `permissions` is pinned BY VALUE.
    for key in sorted(_root_keys(workflow) - {"name", "on", "permissions", "jobs"}):
        problems.append(f"root mapping: unlisted key `{key}`")
    if workflow.get("permissions") != {"contents": "read"}:
        problems.append(f"root permissions: expected `contents: read`, found {workflow.get('permissions')!r}")
    if "concurrency" in workflow:
        problems.append("workflow-level `concurrency` is prohibited")
    if "concurrency" in job:
        problems.append("job-level `concurrency` is prohibited")

    # C1 / C7 — one event, and its options are an allowlist.
    for event in sorted(set(on) - {"pull_request"}):
        problems.append(
            "event set: `merge_group` is prohibited (check_mode=none is a false success)"
            if event == "merge_group" else f"event set: unlisted event `{event}`")
    if "pull_request" not in on:
        problems.append("event set: `pull_request` is absent")
    else:
        for option in sorted(set(on["pull_request"] or {}) - {"branches", "types"}):
            problems.append(f"pull_request options: unlisted option `{option}`"
                            if option not in ("paths", "paths-ignore")
                            else f"pull_request options: `{option}` narrows reachability")
        # C2 — branches, and the activity set.
        if "branches" not in on["pull_request"]:
            problems.append("branches: key is absent")
        if "types" not in on["pull_request"]:
            problems.append("types: key is absent")
        elif "edited" not in on["pull_request"]["types"]:
            problems.append("types: `edited` is missing from the activity set")

    # C3 — the JOB mapping is an allowlist, and nothing skips or masks.
    allowed_job = {"runs-on", "timeout-minutes", "permissions", "steps", "name"}
    if milestone == "M2":
        allowed_job |= M2_ADVISORY_EXEMPTION
    for key in sorted(set(job) - allowed_job):
        problems.append(f"job mapping: unlisted key `{key}`")
    if job.get("permissions") != {"contents": "read"}:
        problems.append(f"job permissions: expected `contents: read`, found {job.get('permissions')!r}")
    if "if" in job:
        problems.append("job: `if:` is prohibited (a skipped job reports Success)")
    if milestone != "M2" and job.get("continue-on-error"):
        problems.append("job: `continue-on-error:` is prohibited")
    if "defaults" in workflow:
        problems.append("workflow `defaults.run` is prohibited")
    if "defaults" in job:
        problems.append("job `defaults.run` is prohibited")
    if job.get("runs-on") != EXPECTED_RUNNER:
        problems.append(f"job: expected `runs-on: {EXPECTED_RUNNER}`, found {job.get('runs-on')!r}")
    if job.get("timeout-minutes") != EXPECTED_TIMEOUT_MINUTES:
        problems.append(f"job: expected `timeout-minutes: {EXPECTED_TIMEOUT_MINUTES}`, "
                        f"found {job.get('timeout-minutes')!r}")

    invocations = sum(1 for step in steps if ACTION_PIN.split("@")[0] in str(step.get("uses", "")))
    if invocations != 1:
        problems.append(f"steps: expected exactly one Trunk invocation, found {invocations}")

    # C8 — the step sequence is an allowlist, in order.
    if names != EXPECTED_STEPS:
        for expected in EXPECTED_STEPS:
            if expected not in names:
                problems.append(f"step sequence: `{expected}` is absent")
        for actual in names:
            if actual not in EXPECTED_STEPS:
                problems.append(f"step sequence: unexpected step before `trunk`")
        if sorted(filter(None, names)) == sorted(EXPECTED_STEPS) and names != EXPECTED_STEPS:
            problems.append("step sequence: `guard-launcher-path` is not immediately before `trunk`")

    for step in steps:
        label = step.get("name")
        for key in sorted({"if", "continue-on-error", "shell", "working-directory", "env", "id"} & set(step)):
            problems.append(f"step `{label}`: unlisted key `{key}`"
                            if key == "id" else f"step `{label}`: `{key}:` is prohibited")
        body = step.get("run", "")
        if "GITHUB_ENV" in body:
            problems.append(f"step `{label}`: writes to $GITHUB_ENV")
        if "GITHUB_PATH" in body:
            problems.append(f"step `{label}`: writes to $GITHUB_PATH")
        # Only the C6 guard may NAME a launcher path; any other body mentioning one is planting it.
        # C6's guard inspects the tree once, so a body that creates a path is the hole the guard's
        # adjacency to the action exists to close, from inside a step the sequence allows.
        if label != "guard-launcher-path" and any(path in body for path in C6_GUARDED_PATHS):
            problems.append(f"step `{label}`: creates a prohibited launcher path")

    # C5 — no `env:` at workflow, job OR step scope.
    if "env" in workflow:
        problems.append("workflow-level `env:` is prohibited")
    if "env" in job:
        problems.append("job-level `env:` is prohibited")

    # C8 — checkout inputs are allowlisted too, with two REQUIRED-PRESENT members.
    if "checkout" in names:
        checkout = _step(workflow, "checkout").get("with", {})
        for key in sorted(set(checkout) - {"fetch-depth", "lfs", "persist-credentials"}):
            problems.append(f"checkout inputs: unlisted input `{key}`")
        if "lfs" not in checkout:
            problems.append("checkout inputs: `lfs` is absent")
        elif checkout["lfs"] is not True:
            problems.append("checkout inputs: `lfs` must be true")
        if "persist-credentials" not in checkout:
            problems.append("checkout inputs: `persist-credentials` is absent")
        elif checkout["persist-credentials"] is not False:
            problems.append("checkout inputs: `persist-credentials` must be false")

    # C4 / C9 — the action's inputs are an allowlist, and the action is pinned by exact SHA.
    if "trunk" in names:
        trunk = _step(workflow, "trunk")
        if trunk.get("uses") != ACTION_PIN:
            problems.append("action pin: not pinned to the expected SHA"
                            if "@" in str(trunk.get("uses")) and len(str(trunk.get("uses")).split("@")[-1]) == 40
                            else "action pin: `trunk-io/trunk-action` is not pinned by SHA")
        used = trunk.get("with", {})
        for key in sorted(set(used) - {"arguments", "save-annotations", "cache", "cache-key"}):
            problems.append(f"action inputs: unlisted input `{key}`")
        if "arguments" not in used:
            problems.append("action inputs: `arguments` is absent")
        elif used["arguments"] != ARGUMENTS_LITERAL:
            problems.append("action inputs: `arguments` does not equal the declared literal")
        if "save-annotations" not in used:
            problems.append("action inputs: `save-annotations` is absent")
        elif used["save-annotations"] is not True:
            problems.append("action inputs: `save-annotations` must be true")

    # C6 — every guarded path is named in the guard that runs last before the action.
    if "guard-launcher-path" in names:
        guard = _step(workflow, "guard-launcher-path").get("run", "")
        for path in C6_GUARDED_PATHS:
            if path not in guard:
                problems.append(f"C6 guard: does not cover {path}")

    return problems


class Cell9_TheShippedWorkflowMeetsItsContract(unittest.TestCase):
    """The job block prohibits what COREDEV-2771 measured, and satisfies C0-C9 and C6a."""

    @classmethod
    def setUpClass(cls):
        cls.workflow = _load_workflow()

    def test_shipped_workflow_has_no_contract_problems_at_m2(self):
        self.assertEqual([], contract_problems(self.workflow, milestone="M2"))

    def test_the_only_m3_problem_is_the_declared_advisory_exemption(self):
        """M2's exemption is real and SCOPED: removing that ONE key makes the workflow M3-clean.

        The clauses OVERLAP by design — `continue-on-error` violates both C3's job-mapping allowlist
        and C3's explicit prohibition — so the honest assertion is not "exactly one diagnostic" but
        "every M3 diagnostic names this key, and deleting it leaves none". Demanding non-overlap would
        make most mutants unconstructible.
        """
        problems = contract_problems(self.workflow, milestone="M3")
        self.assertNotEqual([], problems)
        for problem in problems:
            self.assertIn("continue-on-error", problem)
        at_m3 = copy.deepcopy(self.workflow)
        at_m3["jobs"][EXPECTED_CONTEXT].pop("continue-on-error")
        self.assertEqual([], contract_problems(at_m3, milestone="M3"))

    def test_advisory_exemption_is_job_scoped_not_step_scoped(self):
        """Step scope would rewrite the Trunk step's conclusion to success and make cell 2 blind."""
        self.assertIs(True, _job(self.workflow).get("continue-on-error"))
        for step in _steps(self.workflow):
            self.assertNotIn("continue-on-error", step, f"step {step.get('name')!r}")


class Cell6a_TheResolverIsPinnedBeforeItExecutes(unittest.TestCase):
    """C6a — the digest is verified BEFORE the step that runs the script, not merely before the action."""

    @classmethod
    def setUpClass(cls):
        cls.workflow = _load_workflow()

    def test_the_pinned_digest_matches_the_shipped_resolver(self):
        guard = _step(self.workflow, "guard-resolver-digest")["run"]
        pinned = re.search(r"expected='([a-f0-9]{64})'", guard)
        self.assertIsNotNone(pinned, "the C6a guard must pin a sha256 literal")
        self.assertEqual(_sha256_file(RESOLVER_PATH), pinned.group(1))

    def test_the_digest_guard_precedes_the_step_that_executes_the_resolver(self):
        names = [step.get("name") for step in _steps(self.workflow)]
        executor = next(step for step in _steps(self.workflow)
                        if "resolve-trunk-range.sh" in step.get("run", "") and step["name"] != "guard-resolver-digest")
        self.assertLess(names.index("guard-resolver-digest"), names.index(executor["name"]))

    def test_the_c6_guard_is_last_before_the_action(self):
        names = [step.get("name") for step in _steps(self.workflow)]
        self.assertEqual(names.index("guard-launcher-path"), names.index("trunk") - 1)


class Cell10_PermissionsArePinnedByValueAtBothScopes(unittest.TestCase):
    """The STATIC half. A wider token produces byte-identical runtime evidence, so only this sees it."""

    def test_permissions_pinned_at_root_and_job(self):
        workflow = _load_workflow()
        self.assertEqual({"contents": "read"}, workflow.get("permissions"))
        self.assertEqual({"contents": "read"}, _job(workflow).get("permissions"))


class Cell14_ExactlyOneProducerOfTheContext(unittest.TestCase):
    """Keying on the JOB ID alone is the wrong identifier: a job declared `jobs.other` with
    `name: trunk-check` produces exactly the same required context."""

    @staticmethod
    def _producers(workflows: dict[str, dict]) -> list[str]:
        found = []
        for path, workflow in workflows.items():
            for job_id, job in (workflow.get("jobs") or {}).items():
                explicit = job.get("name")
                if explicit is not None and not isinstance(explicit, str):
                    raise AssertionError(f"{path}: job {job_id} has a non-string name")
                if explicit and ("${{" in explicit):
                    # FAIL CLOSED: a static census cannot resolve an expression-valued name.
                    raise AssertionError(f"{path}: job {job_id} has an expression-valued name")
                if (explicit or job_id) == EXPECTED_CONTEXT:
                    found.append(f"{path}:{job_id}")
        return found

    def _tree(self) -> dict[str, dict]:
        return {p.name: yaml.safe_load(p.read_text(encoding="utf-8"))
                for p in sorted((REPO / ".github/workflows").glob("*.yml"))}

    def test_exactly_one_producer_repo_wide(self):
        self.assertEqual(["trunk-check.yml:trunk-check"], self._producers(self._tree()))

    def test_a_second_producer_under_a_different_job_id_is_detected(self):
        tree = self._tree()
        tree["decoy.yml"] = {"jobs": {"something-else": {"name": EXPECTED_CONTEXT}}}
        self.assertEqual(2, len(self._producers(tree)))

    def test_zero_producers_is_detected(self):
        self.assertEqual([], self._producers({"none.yml": {"jobs": {"other": {}}}}))

    def test_an_expression_valued_name_fails_closed(self):
        with self.assertRaises(AssertionError):
            self._producers({"x.yml": {"jobs": {"j": {"name": "${{ matrix.n }}"}}}})


class Cell15_RunnerTimeoutAndRegistryAgreement(unittest.TestCase):
    def setUp(self):
        self.workflow = _load_workflow()
        self.registry = yaml.safe_load(REGISTRY_PATH.read_text(encoding="utf-8"))

    def test_runner_and_concrete_timeout(self):
        job = _job(self.workflow)
        self.assertEqual(EXPECTED_RUNNER, job["runs-on"])
        # A CONCRETE ceiling, asserted as an operand: `timeout-minutes: 360` is GitHub's own default.
        self.assertEqual(EXPECTED_TIMEOUT_MINUTES, job["timeout-minutes"])
        self.assertNotEqual(360, job["timeout-minutes"])

    def test_registry_pins_the_same_action_as_the_workflow(self):
        self.assertEqual(ACTION_PIN.split("@")[1], self.registry["action_pin"].split("@")[1])
        self.assertEqual(ACTION_PIN, _step(self.workflow, "trunk")["uses"])

    def test_registry_entry_paths_match_the_shipped_workflow(self):
        required = self.registry["entries"]["required"]
        self.assertEqual(".github/workflows/trunk-check.yml", required["path"])
        self.assertEqual(EXPECTED_CONTEXT, required["job"])
        self.assertTrue(required["required_context"])

    def test_resolve_is_entry_agnostic_and_resolved_once(self):
        """The signature IS the enforcement: with no entry id reaching resolve(), a per-entry private
        resolver cannot be written behind it. Two weaker encodings failed here."""
        implementation = self.registry["families"]["target_set_resolution"]["implementation"]
        self.assertTrue(implementation["entry_agnostic"])
        self.assertTrue(implementation["resolved_once_before_entry_selection"])
        self.assertNotIn("entry", implementation["function"].split("(")[1])


class Cell15_TargetSetResolution(unittest.TestCase):
    """resolve() = include MINUS exclude, aliases expanded, patterns FAIL CLOSED."""

    def test_alias_and_prefix_are_expanded(self):
        self.assertEqual({"main", "alpha"}, _resolve_ref_name(
            {"include": ["~DEFAULT_BRANCH", "refs/heads/alpha"], "exclude": []}, "main"))

    def test_exclude_vetoes(self):
        """An exclude-blind resolver measures a set STRICTLY LARGER than the one in force."""
        self.assertEqual({"main"}, _resolve_ref_name(
            {"include": ["~DEFAULT_BRANCH", "refs/heads/alpha"], "exclude": ["refs/heads/alpha"]}, "main"))

    def test_a_same_cardinality_default_branch_retarget_is_visible(self):
        """No string in the repository changes, which is why a literal comparison cannot see it."""
        self.assertEqual({"trunk", "alpha"}, _resolve_ref_name(
            {"include": ["~DEFAULT_BRANCH", "refs/heads/alpha"], "exclude": []}, "trunk"))

    def test_patterns_and_all_fail_closed_on_both_sides(self):
        for side in ("include", "exclude"):
            for payload in ("~ALL", "refs/heads/a*", "refs/heads/alph?", "refs/heads/alph[a-z]"):
                with self.subTest(side=side, payload=payload):
                    ref_name = {"include": ["refs/heads/main"], "exclude": []}
                    ref_name[side] = ref_name[side] + [payload]
                    with self.assertRaises(ValueError):
                        _resolve_ref_name(ref_name, "main")

    def test_the_shipped_workflow_matches_the_live_resolved_set(self):
        on = _on(_load_workflow())["pull_request"]
        self.assertEqual(_resolve_target_set(), set(on["branches"]))


class Cell4_TheLinterSetMembershipIsFrozen(unittest.TestCase):
    """A membership oracle over the configuration, and NOTHING MORE — a static parse cannot show that
    shellcheck actually diagnosed anything. Execution coverage is out of scope (COREDEV-2787)."""

    def setUp(self):
        self.config = TRUNK_CONFIG.read_text(encoding="utf-8")
        self.enabled = yaml.safe_load(self.config)["lint"]["enabled"]
        self.names = {entry.split("@")[0] for entry in self.enabled}

    def test_the_nineteen_required_linters_are_all_enabled(self):
        self.assertEqual(set(), EXPECTED_LINTERS - self.names)

    def test_no_unlisted_linter_appears(self):
        self.assertEqual(set(), self.names - EXPECTED_LINTERS - {EXCLUDED_LINTER})

    def test_the_declared_exclusion_is_configured_but_filtered_from_the_required_job(self):
        self.assertIn(EXCLUDED_LINTER, self.names)
        self.assertEqual(
            ARGUMENTS_LITERAL,
            _step(_load_workflow(), "trunk")["with"]["arguments"],
        )
        self.assertIn(EXCLUDED_LINTER, ARGUMENTS_LITERAL)

    def test_a_reduced_configuration_is_detected(self):
        """The revision-5 wording — "the configured set minus the exclusions" — could not do this."""
        reduced = [entry for entry in self.enabled if not entry.startswith("shellcheck")]
        self.assertNotEqual(set(), EXPECTED_LINTERS - {e.split("@")[0] for e in reduced})

    def test_a_version_only_bump_does_not_move_the_normalised_digest(self):
        bumped = self.config.replace("zizmor@1.29.0", "zizmor@9.99.9")
        self.assertNotEqual(self.config, bumped, "fixture must actually change the file")
        self.assertEqual(_normalised_lint_block(self.config), _normalised_lint_block(bumped))

    def test_a_command_override_does_move_the_normalised_digest(self):
        """Names alone were not enough: a PR can keep all 19 and disable every linter by overriding
        `commands[].run` to `exit 0`, widening `success_codes`, or adding a global `ignore`."""
        block = yaml.safe_load(self.config)
        block["lint"]["definitions"][0]["commands"][0]["run"] = "exit 0"
        overridden = yaml.safe_dump(block)
        self.assertNotEqual(_normalised_lint_block(self.config), _normalised_lint_block(overridden))


class Cell11_MutantsAreGeneratedFromTheRegistry(unittest.TestCase):
    """One mutant per mutation CASE, keyed by id — never a hand-written list.

    This class executes the `yaml`-kind cases, which are the ones a workflow-parsing owner can
    construct and evaluate. The `repo_fixture`, `content_digest` and `remote_relation` kinds need a
    checked-out tree, a real run or an authenticated ruleset read, and are owned elsewhere (M2b/M2c and
    the rollout evidence artifact); they are reported here as deferred rather than silently counted, so
    this cell never reads as covering more than it does.
    """

    @classmethod
    def setUpClass(cls):
        cls.registry = yaml.safe_load(REGISTRY_PATH.read_text(encoding="utf-8"))
        cls.workflow = _load_workflow()

    def test_every_case_declares_the_five_required_fields(self):
        for obligation in self.registry["obligations"]:
            for case in obligation.get("cases", []):
                with self.subTest(case=case["id"]):
                    for field in ("op", "side", "target", "validity", "diagnostic"):
                        self.assertIn(field, case)

    def test_case_ids_are_unique_and_namespaced_by_their_obligation(self):
        seen = []
        for obligation in self.registry["obligations"]:
            for case in obligation.get("cases", []):
                seen.append(case["id"])
                self.assertTrue(case["id"].startswith(obligation["id"] + "/"), case["id"])
        self.assertEqual(len(seen), len(set(seen)))

    def test_the_registry_covers_every_clause_the_workflow_is_asserted_against(self):
        clauses = {obligation["clause"] for obligation in self.registry["obligations"]}
        for clause in ("C0", "C1", "C2", "C3", "C4", "C5", "C6", "C6a", "C7", "C8", "C9"):
            self.assertIn(clause, clauses)

    # ---- the generated mutants -------------------------------------------------------------------
    # Each entry is (case id, mutate(workflow), expected diagnostic). The mutation is applied to a deep
    # copy of the SHIPPED workflow, so a case that cannot be constructed fails loudly here rather than
    # silently passing.
    def _yaml_mutants(self):
        def at_root(key, value):
            def apply(w): w[key] = value
            return apply

        def at_job(key, value):
            def apply(w): _job(w)[key] = value
            return apply

        def drop_job(key):
            def apply(w): _job(w).pop(key, None)
            return apply

        def at_event(key, value):
            def apply(w): _on(w)["pull_request"][key] = value
            return apply

        def at_with(step, key, value):
            def apply(w): _step(w, step).setdefault("with", {})[key] = value
            return apply

        def drop_with(step, key):
            def apply(w): _step(w, step)["with"].pop(key, None)
            return apply

        return [
            ("C0.permissions-pinned-at-root/write-all", at_root("permissions", "write-all"),
             "root permissions: expected `contents: read`, found 'write-all'"),
            ("C0.permissions-pinned-at-root/absent", lambda w: w.pop("permissions"),
             "root permissions: expected `contents: read`, found None"),
            ("C0.no-concurrency/workflow", at_root("concurrency", {"group": "x"}),
             "workflow-level `concurrency` is prohibited"),
            ("C0.no-concurrency/job", at_job("concurrency", {"group": "x"}),
             "job-level `concurrency` is prohibited"),
            ("C0.root-mapping-allowlist/arbitrary-key", at_root("schedule", []),
             "root mapping: unlisted key `schedule`"),
            ("C1.single-event/add-workflow-dispatch",
             lambda w: _on(w).update({"workflow_dispatch": {}}),
             "event set: unlisted event `workflow_dispatch`"),
            ("C1.single-event/arbitrary-event", lambda w: _on(w).update({"schedule": []}),
             "event set: unlisted event `schedule`"),
            ("C7.no-merge-group/present", lambda w: _on(w).update({"merge_group": {}}),
             "event set: `merge_group` is prohibited (check_mode=none is a false success)"),
            ("C1.event-option-allowlist/paths", at_event("paths", ["**.py"]),
             "pull_request options: `paths` narrows reachability"),
            ("C1.event-option-allowlist/arbitrary-option", at_event("branches-ignore", ["x"]),
             "pull_request options: unlisted option `branches-ignore`"),
            ("C2.branches-equal-resolved-target-set/absent",
             lambda w: _on(w)["pull_request"].pop("branches"), "branches: key is absent"),
            ("C2.types-required/reduced-to-default",
             at_event("types", ["opened", "synchronize", "reopened"]),
             "types: `edited` is missing from the activity set"),
            ("C2.types-required/removed", lambda w: _on(w)["pull_request"].pop("types"),
             "types: key is absent"),
            ("C3.job-mapping-allowlist/arbitrary-key", at_job("container", "ubuntu:24.04"),
             "job mapping: unlisted key `container`"),
            ("C3.job-mapping-allowlist/needs", at_job("needs", ["support"]),
             "job mapping: unlisted key `needs`"),
            ("C3.job-mapping-allowlist/strategy-matrix", at_job("strategy", {"matrix": {"n": [1, 2]}}),
             "job mapping: unlisted key `strategy`"),
            ("C3.permissions-pinned-at-job/write-all", at_job("permissions", "write-all"),
             "job permissions: expected `contents: read`, found 'write-all'"),
            ("C3.permissions-pinned-at-job/absent", drop_job("permissions"),
             "job permissions: expected `contents: read`, found None"),
            ("C3.nothing-skips-or-masks/job-if", at_job("if", "false"),
             "job: `if:` is prohibited (a skipped job reports Success)"),
            ("C3.no-defaults-run/workflow", at_root("defaults", {"run": {"shell": "sh"}}),
             "workflow `defaults.run` is prohibited"),
            ("C3.no-defaults-run/job", at_job("defaults", {"run": {"shell": "sh"}}),
             "job `defaults.run` is prohibited"),
            ("C3.exactly-one-trunk-invocation/two",
             lambda w: _steps(w).append(copy.deepcopy(_step(w, "trunk"))),
             "steps: expected exactly one Trunk invocation, found 2"),
            ("C5.no-env-any-scope/workflow", at_root("env", {"TRUNK_PATH": "/bin/true"}),
             "workflow-level `env:` is prohibited"),
            ("C5.no-env-any-scope/job", at_job("env", {"TRUNK_PATH": "/bin/true"}),
             "job-level `env:` is prohibited"),
            ("C5.no-env-any-scope/step",
             lambda w: _step(w, "trunk").update({"env": {"TRUNK_PATH": "/bin/true"}}),
             "step `trunk`: `env:` is prohibited"),
            ("C4.with-inputs-allowlist/trunk-path", at_with("trunk", "trunk-path", "/bin/true"),
             "action inputs: unlisted input `trunk-path`"),
            ("C4.with-inputs-allowlist/post-init", at_with("trunk", "post-init", "echo hi"),
             "action inputs: unlisted input `post-init`"),
            ("C4.with-inputs-allowlist/arbitrary-input", at_with("trunk", "check-mode", "popular"),
             "action inputs: unlisted input `check-mode`"),
            ("C4.arguments-required-literal/absent", drop_with("trunk", "arguments"),
             "action inputs: `arguments` is absent"),
            ("C4.arguments-required-literal/appended",
             at_with("trunk", "arguments", ARGUMENTS_LITERAL + " --fix"),
             "action inputs: `arguments` does not equal the declared literal"),
            ("C4.save-annotations-required/absent", drop_with("trunk", "save-annotations"),
             "action inputs: `save-annotations` is absent"),
            ("C4.save-annotations-required/false", at_with("trunk", "save-annotations", False),
             "action inputs: `save-annotations` must be true"),
            ("C8.checkout-inputs-allowlist/sparse-checkout",
             at_with("checkout", "sparse-checkout", "scripts/"),
             "checkout inputs: unlisted input `sparse-checkout`"),
            ("C8.checkout-inputs-allowlist/ref", at_with("checkout", "ref", "main"),
             "checkout inputs: unlisted input `ref`"),
            ("C8.checkout-inputs-allowlist/filter", at_with("checkout", "filter", "blob:none"),
             "checkout inputs: unlisted input `filter`"),
            ("C8.checkout-inputs-allowlist/lfs-removed", drop_with("checkout", "lfs"),
             "checkout inputs: `lfs` is absent"),
            ("C8.checkout-inputs-allowlist/lfs-false", at_with("checkout", "lfs", False),
             "checkout inputs: `lfs` must be true"),
            ("C8.checkout-inputs-allowlist/persist-credentials-removed",
             drop_with("checkout", "persist-credentials"),
             "checkout inputs: `persist-credentials` is absent"),
            ("C8.checkout-inputs-allowlist/persist-credentials-true",
             at_with("checkout", "persist-credentials", True),
             "checkout inputs: `persist-credentials` must be false"),
            ("C9.action-pinned-by-sha/tag",
             lambda w: _step(w, "trunk").update({"uses": "trunk-io/trunk-action@v2.0.0"}),
             "action pin: `trunk-io/trunk-action` is not pinned by SHA"),
            ("C9.action-pinned-by-sha/different-sha",
             lambda w: _step(w, "trunk").update({"uses": "trunk-io/trunk-action@" + "0" * 40}),
             "action pin: not pinned to the expected SHA"),
            ("C8.step-sequence-allowlist/delete-guard-launcher-path",
             lambda w: _steps(w).remove(_step(w, "guard-launcher-path")),
             "step sequence: `guard-launcher-path` is absent"),
            ("C8.step-sequence-allowlist/delete-guard-empty-diff",
             lambda w: _steps(w).remove(_step(w, "guard-empty-diff")),
             "step sequence: `guard-empty-diff` is absent"),
            ("C8.step-sequence-allowlist/delete-guard-resolver-digest",
             lambda w: _steps(w).remove(_step(w, "guard-resolver-digest")),
             "step sequence: `guard-resolver-digest` is absent"),
            ("C8.run-bodies-frozen/github-env-trunk-path",
             lambda w: _step(w, "guard-empty-diff").update(
                 {"run": _step(w, "guard-empty-diff")["run"] + '\necho X >> "$GITHUB_ENV"'}),
             "step `guard-empty-diff`: writes to $GITHUB_ENV"),
            ("C8.run-bodies-frozen/github-path",
             lambda w: _step(w, "guard-empty-diff").update(
                 {"run": _step(w, "guard-empty-diff")["run"] + '\necho X >> "$GITHUB_PATH"'}),
             "step `guard-empty-diff`: writes to $GITHUB_PATH"),
            ("C8.run-bodies-frozen/changed-shell",
             lambda w: _step(w, "guard-empty-diff").update({"shell": "sh"}),
             "step `guard-empty-diff`: `shell:` is prohibited"),
            ("C8.run-bodies-frozen/changed-working-directory",
             lambda w: _step(w, "guard-empty-diff").update({"working-directory": "/tmp"}),
             "step `guard-empty-diff`: `working-directory:` is prohibited"),
            ("C8.step-sequence-allowlist/arbitrary-step-key",
             lambda w: _step(w, "guard-empty-diff").update({"id": "x"}),
             "step `guard-empty-diff`: unlisted key `id`"),
            ("C3.nothing-skips-or-masks/step-continue-on-error",
             lambda w: _step(w, "trunk").update({"continue-on-error": True}),
             "step `trunk`: `continue-on-error:` is prohibited"),
            # ---- the sixteen this cell's own coverage check found missing -------------------------
            ("C0.permissions-pinned-at-root/widened-scope",
             at_root("permissions", {"contents": "read", "checks": "write"}),
             "root permissions: expected `contents: read`, found {'contents': 'read', 'checks': 'write'}"),
            ("C3.permissions-pinned-at-job/widened-scope",
             at_job("permissions", {"contents": "read", "checks": "write"}),
             "job permissions: expected `contents: read`, found {'contents': 'read', 'checks': 'write'}"),
            ("C1.single-event/add-push",
             lambda w: _on(w).update({"push": {"branches": ["main"]}}),
             "event set: unlisted event `push`"),
            ("C1.single-event/remove-pull-request", lambda w: _on(w).pop("pull_request"),
             "event set: `pull_request` is absent"),
            ("C1.event-option-allowlist/paths-ignore", at_event("paths-ignore", ["docs/**"]),
             "pull_request options: `paths-ignore` narrows reachability"),
            # Only a violation once M2's advisory exemption lapses at M3 — which is the point of
            # writing the case at M2 and ENABLING it at M3.
            ("C3.nothing-skips-or-masks/job-continue-on-error", lambda w: None,
             "job: `continue-on-error:` is prohibited", "M3"),
            ("C3.exactly-one-trunk-invocation/zero",
             lambda w: _steps(w).remove(_step(w, "trunk")),
             "steps: expected exactly one Trunk invocation, found 0"),
            ("C8.step-sequence-allowlist/extra-step",
             lambda w: _steps(w).insert(4, {"name": "extra", "run": "echo hi"}),
             "step sequence: unexpected step before `trunk`"),
            ("C8.step-sequence-allowlist/guard-moved",
             lambda w: _steps(w).insert(2, _steps(w).pop(3)),
             "step sequence: `guard-launcher-path` is not immediately before `trunk`"),
            ("C8.step-sequence-allowlist/delete-checkout",
             lambda w: _steps(w).remove(_step(w, "checkout")),
             "step sequence: `checkout` is absent"),
            ("C8.step-sequence-allowlist/delete-trunk",
             lambda w: _steps(w).remove(_step(w, "trunk")),
             "step sequence: `trunk` is absent"),
            ("C8.run-bodies-frozen/github-env-bash-env",
             lambda w: _step(w, "guard-empty-diff").update(
                 {"run": _step(w, "guard-empty-diff")["run"] + '\necho BASH_ENV=/tmp/x >> "$GITHUB_ENV"'}),
             "step `guard-empty-diff`: writes to $GITHUB_ENV"),
            ("C8.run-bodies-frozen/creates-c6-path",
             lambda w: _step(w, "guard-empty-diff").update(
                 {"run": _step(w, "guard-empty-diff")["run"] + "\ninstall -D /bin/true tools/trunk"}),
             "step `guard-empty-diff`: creates a prohibited launcher path"),
            ("C8.checkout-inputs-allowlist/repository", at_with("checkout", "repository", "other/repo"),
             "checkout inputs: unlisted input `repository`"),
            ("C8.checkout-inputs-allowlist/path", at_with("checkout", "path", "sub"),
             "checkout inputs: unlisted input `path`"),
            ("C8.checkout-inputs-allowlist/arbitrary-input", at_with("checkout", "submodules", True),
             "checkout inputs: unlisted input `submodules`"),
        ]

    def test_the_shipped_workflow_is_a_passing_positive_control(self):
        """Every mutant below starts from a GREEN baseline, or it proves nothing."""
        self.assertEqual([], contract_problems(copy.deepcopy(self.workflow), milestone="M2"))

    def test_every_generated_mutant_fails_with_its_own_diagnostic(self):
        for case in self._yaml_mutants():
            case_id, mutate, diagnostic = case[0], case[1], case[2]
            milestone = case[3] if len(case) > 3 else "M2"
            with self.subTest(case=case_id):
                mutant = copy.deepcopy(self.workflow)
                mutate(mutant)
                if milestone == "M2":
                    # At M3 one case asserts that the SHIPPED advisory key is itself the violation,
                    # so it mutates nothing by design; every other case must really change the file.
                    self.assertNotEqual(
                        yaml.safe_dump(self.workflow, sort_keys=True),
                        yaml.safe_dump(mutant, sort_keys=True),
                        "the mutant must actually change the workflow",
                    )
                problems = contract_problems(mutant, milestone=milestone)
                self.assertIn(diagnostic, problems, f"{case_id} did not produce its own diagnostic")

    def test_every_generated_mutant_names_a_declared_registry_case(self):
        declared = {case["id"]
                    for obligation in self.registry["obligations"]
                    for case in obligation.get("cases", [])}
        for case in self._yaml_mutants():
            with self.subTest(case=case[0]):
                self.assertIn(case[0], declared)

    def test_every_declared_case_is_executed_here_or_provably_needs_external_machinery(self):
        """No silent gap between what the registry declares and what this cell runs.

        Classification is PER CASE, not per obligation: `C8.run-bodies-frozen` is a `content_digest`
        obligation whose `shell`, `working-directory`, `$GITHUB_ENV` and `$GITHUB_PATH` cases are
        plain structural checks a parser can evaluate, while its `body-digest-*` cases genuinely need
        the digest mechanism. Bucketing by obligation kind would have deferred the four this cell
        already kills — reporting LESS coverage than exists, which is the mirror of the defect this
        test exists to prevent.
        """
        executed = {case[0] for case in self._yaml_mutants()}
        declared, deferred = set(), []
        for obligation in self.registry["obligations"]:
            for case in obligation.get("cases", []):
                declared.add(case["id"])
                if case["id"] in executed:
                    continue
                deferred.append((case["id"], obligation["kind"], case["op"], case["side"],
                                 obligation.get("entries", [])))
        self.assertTrue(executed <= declared)
        for case_id, kind, op, side, entries in deferred:
            with self.subTest(case=case_id):
                # A deferred case must NEED a tree, a real run, an authenticated remote read, or an
                # ENTRY THIS MILESTONE HAS NOT SHIPPED — the canary is M2b. Anything else is a gap.
                self.assertTrue(
                    op in ("materialise", "edit_bytes") or side == "remote"
                    or kind in ("repo_fixture", "remote_relation")
                    or "required" not in entries,
                    f"{case_id} ({kind}/{op}/{side}) is executable here and must not be deferred",
                )
        self.assertGreater(len(executed), 0)
        self.assertGreater(len(deferred), 0)


class SurvivorCorpusIsIntactAndIndependent(unittest.TestCase):
    """A registry edit that silently drops an obligation must red something the rendering lint cannot
    see, so the corpus is maintained independently and never resolves through a registry id."""

    def setUp(self):
        self.survivors = yaml.safe_load(SURVIVORS_PATH.read_text(encoding="utf-8"))

    def test_every_survivor_is_self_contained(self):
        for entry in self.survivors["survivors"]:
            with self.subTest(survivor=entry["id"]):
                for field in ("found_in_round", "survived_formulation", "mutant",
                              "would_have_shipped", "must_fail_because"):
                    self.assertIn(field, entry)

    def test_the_corpus_does_not_resolve_through_the_registry(self):
        registry_ids = {case["id"]
                        for obligation in yaml.safe_load(REGISTRY_PATH.read_text(encoding="utf-8"))["obligations"]
                        for case in obligation.get("cases", [])}
        for entry in self.survivors["survivors"]:
            self.assertNotIn(entry["id"], registry_ids)


if __name__ == "__main__":  # pragma: no cover
    unittest.main()
